ResNet50_Layer_Names = {0: "input_1",
                        2: "conv1",
                        3: "bn_conv1",
                        4: "activation_1",
                        5: "max_pooling2d_1",
                        17: "activation_4",
                        27: "activation_7",
                        37: "activation_10",
                        49: "activation_13",
                        59: "activation_16",
                        69: "activation_19",
                        79: "activation_22",
                        91: "activation_25",
                        101: "activation_28",
                        111: "activation_31",
                        121: "activation_34",
                        131: "activation_37",
                        141: "activation_40",
                        153: "activation_43",
                        163: "activation_46",
                        173: "activation_49",
                        177: "dense_2"}

InceptionV3_Layer_Names = {0: "input_1",
                           4: "conv2d_1",
                           7: "conv2d_2",
                           10: "conv2d_3",
                           11: "max_pooling2d_1",
                           14: "conv2d_4",
                           17: "conv2d_5",
                           18: "max_pooling2d_2",
                           41: "mixed0",
                           64: "mixed1",
                           87: "mixed2",
                           101: "mixed3",
                           133: "mixed4",
                           165: "mixed5",
                           197: "mixed6",
                           229: "mixed7",
                           249: "mixed8",
                           280: "mixed9",
                           311: "mixed10",
                           313: "dense_2"}

MobileNets_Layer_Names = {0:"input_1",
                          3:"conv1_relu",
                          9:"conv_pw_1_relu",
                          15:"conv_pw_2_relu",
                          21:"conv_pw_3_relu",
                          27:"conv_pw_4_relu",
                          33:"conv_pw_5_relu",
                          39:"conv_pw_6_relu",
                          45:"conv_pw_7_relu",
                          51:"conv_pw_8_relu",
                          57:"conv_pw_9_relu",
                          63:"conv_pw_10_relu",
                          69:"conv_pw_11_relu",
                          75:"conv_pw_12_relu",
                          81:"conv_pw_13_relu",
                          84:"dense_2"}

Yolo_Layer_Names = {0:"input_1",
                    1:"conv2d_1",
                    2:"batch_normalization_1",
                    3:"leaky_re_lu_1",
                    4:"max_pooling2d_1",
                    5:"conv2d_2",
                    6:"batch_normalization_2",
                    7:"leaky_re_lu_2",
                    8:"max_pooling2d_2",
                    9:"conv2d_3",
                    10:"batch_normalization_3",
                    11:"leaky_re_lu_3",
                    12:"conv2d_4",
                    13:"batch_normalization_4",
                    14:"leaky_re_lu_4",
                    15:"conv2d_5",
                    16:"batch_normalization_5",
                    17:"leaky_re_lu_5",
                    18:"max_pooling2d_3",
                    19:"conv2d_6",
                    20:"batch_normalization_6",
                    21:"leaky_re_lu_6",
                    22:"conv2d_7",
                    23:"batch_normalization_7",
                    24:"leaky_re_lu_7",
                    25:"conv2d_8",
                    26:"batch_normalization_8",
                    27:"leaky_re_lu_8",
                    28:"max_pooling2d_4",
                    29:"conv2d_9",
                    30:"batch_normalization_9",
                    31:"leaky_re_lu_9",
                    32:"conv2d_10",
                    33:"batch_normalization_10",
                    34:"leaky_re_lu_10",
                    35:"conv2d_11",
                    36:"batch_normalization_11",
                    37:"leaky_re_lu_11",
                    38:"conv2d_12",
                    39:"batch_normalization_12",
                    40:"leaky_re_lu_12",
                    41:"conv2d_13",
                    42:"batch_normalization_13",
                    43:"leaky_re_lu_13",
                    44:"max_pooling2d_5",
                    45:"conv2d_14",
                    46:"batch_normalization_14",
                    47:"leaky_re_lu_14",
                    48:"conv2d_15",
                    49:"batch_normalization_15",
                    50:"leaky_re_lu_15",
                    51:"conv2d_16",
                    52:"batch_normalization_16",
                    53:"leaky_re_lu_16",
                    54:"conv2d_17",
                    55:"batch_normalization_17",
                    56:"leaky_re_lu_17",
                    57:"conv2d_18",
                    58:"batch_normalization_18",
                    59:"leaky_re_lu_18",
                    60:"conv2d_19",
                    61:"batch_normalization_19",
                    62:"conv2d_21",
                    63:"leaky_re_lu_19",
                    64:"batch_normalization_21",
                    #65:"conv2d_20",
                    65:"leaky_re_lu_21",
                    66:"batch_normalization_20",
                    67:"space_to_depth_x2",
                    68:"leaky_re_lu_20",
                    69:"concatenate_1",
                    70:"conv2d_22",
                    71:"batch_normalization_22",
                    72:"leaky_re_lu_22",
                    73:"conv2d_24/BiasAdd"};

inception_info = {"layer_names": InceptionV3_Layer_Names,
                  "num_layers": 314}

yolo_info = {"layer_names": Yolo_Layer_Names,
             "num_layers": 74}
