ResNet50_Layer_Names = {0: "input_1",
                        2: "conv1",
                        3: "bn_conv1",
                        4: "activation_1",
                        5: "max_pooling2d_1",
                        17: "activation_4",
                        27: "activation_7",
                        37: "activation_10",
                        49: "activation_13",
                        59: "activation_16",
                        69: "activation_19",
                        79: "activation_22",
                        91: "activation_25",
                        101: "activation_28",
                        111: "activation_31",
                        121: "activation_34",
                        131: "activation_37",
                        141: "activation_40",
                        153: "activation_43",
                        163: "activation_46",
                        173: "activation_49",
                        177: "dense_2"}

InceptionV3_Layer_Names = {0: "input_1",
                           4: "conv2d_1",
                           7: "conv2d_2",
                           10: "conv2d_3",
                           11: "max_pooling2d_1",
                           14: "conv2d_4",
                           17: "conv2d_5",
                           18: "max_pooling2d_2",
                           41: "mixed0",
                           64: "mixed1",
                           87: "mixed2",
                           101: "mixed3",
                           133: "mixed4",
                           165: "mixed5",
                           197: "mixed6",
                           229: "mixed7",
                           249: "mixed8",
                           280: "mixed9",
                           311: "mixed10",
                           313: "dense_2"}

MobileNets_Layer_Names = {0:"input_1",
                          3:"conv1_relu",
                          9:"conv_pw_1_relu",
                          15:"conv_pw_2_relu",
                          21:"conv_pw_3_relu",
                          27:"conv_pw_4_relu",
                          33:"conv_pw_5_relu",
                          39:"conv_pw_6_relu",
                          45:"conv_pw_7_relu",
                          51:"conv_pw_8_relu",
                          57:"conv_pw_9_relu",
                          63:"conv_pw_10_relu",
                          69:"conv_pw_11_relu",
                          75:"conv_pw_12_relu",
                          81:"conv_pw_13_relu",
                          84:"dense_2"}

Yolo_Layer_Names = {0,"input_1",
                    5,"conv2d_2/convolution",
                    10,"batch_normalization_3/cond/Merge",
                    15,"conv2d_5/convolution",
                    20,"batch_normalization_6/cond/Merge",
                    25,"conv2d_8/convolution",
                    30,"batch_normalization_9/cond/Merge",
                    35,"conv2d_11/convolution",
                    40,"leaky_re_lu_12/sub",
                    45,"leaky_re_lu_13/sub",
                    ##"conv2d_14/convolution",
                    ##"leaky_re_lu_15/sub",
                    ##"batch_normalization_17/cond/Merge",
                    ##"conv2d_19/convolution",
                    ##"conv2d_20/convolution",
                    70:"concatenate_1/concat",
                    73:"conv2d_24/BiasAdd"};
